'\"t
.TH "SSH-MONITOR" "8" "04\ \&MAY\ \&2022" "SSH-MONITOR 1.0" "SSH MONITORING SERVICE"

.SH "NAME"
ssh-monitoring
.SH "DESCRIPTION"
\fBssh-monitoring\fR - service for monitoring users connected to the system via SSH every 30 seconds. When external user connects to the service via SSH, the user gets notified with a message that shows the name of the user connected to the system remotely.
.SH "AUTHORS"
Alexandra Chelnokova