'\"t
.TH "SSH-MONITOR" "8" "01\ \&JUNE\ \&2020" "SSH-MONITOR 1.2" "SSH MONITORING SERVICE"

.SH "NAME"
ssh-monitoring
.SH "DESCRIPTION"
\fBssh-monitoring\fR - service for monitoring users connected to the system via SSH every 30 seconds. When external user connects to the service via SSH, the user gets notified with a message that shows the name of the user connected to the system remotely.
.SH "AUTHORS"
Maxim Grishin,
Nina Ivanova,
Anastasia Khudoyarova,
Elizaveta Nikolaeva,
Anastasia Shaybel